### ISSUE TITLE
Setup chapter skips `keys`

### ISSUE THREAD

**Issue by aitorres** [aquova/chip8-book#10]
On the [Setup](https://github.com/aquova/chip8-book/blob/master/src/3-setup.md) chapter, there should be a section mentioning how keys / the keypad is represented on this implementation.

Up to the [Stack](https://github.com/aquova/chip8-book/blob/master/src/3-setup.md#the-stack) section, keys are not mentioned. Then, the section that comes right after which is [the Timers](https://github.com/aquova/chip8-book/blob/master/src/3-setup.md#the-timers) already includes the `keys` as part of the `Emu` struct with no explanation. I actually missed it until my code editor complained of missing `keys` afterwards in the process.

**Comment by aquova** [comment]
Thanks for pointing this out, I think I must have had this section at some point, but accidentally removed it. I've rewritten a section setting that up.

Fixed in 2ed15402c405bb054146ef9df4cf675ed6db3ebc
