### ISSUE TITLE
Section 4.2 error: character dimensions

### ISSUE THREAD

**Issue by marvincyk** [aquova/chip8-book#11]
From section 4.2 of the book:

> Each character is made up of eight rows of five pixels, with each row using a byte of data, meaning that each letter altogether takes up five bytes of data.

This should either be "five rows of eight pixels" or "eight columns of five pixels".

**Comment by aquova** [comment]
Thanks for catching that! Fixed in e0b3888bed29d5e7201e26c8a8a7cbc3d6becc8f
