### ISSUE TITLE
Error when trying to run on m1

### ISSUE THREAD

**Issue by xMasashi** [aquova/chip8-book#2]
When executing `Cargo run` on Desktop folder:

```
error: linking with `cc` failed: exit status: 1
    = note: ld: library not found for -lSDL2
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by salvatore-giammanco** [comment]
Hello, this is a problem with SDL2 library, here's how i solved (on OSX Intel though):

First I installed sdl2 from homebrew:

```
brew install sdl2
sudo chown root:wheel /usr/local/bin/brew
brew link sdl2
```

Then I had add the library path to LIBRARY_PATH.
Just add this to your bash profile:
```
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"
```

**Comment by aquova** [comment]
It looks like this is an SDL installation error, and not an issue with the instructions in the book. Closing.
