### ISSUE TITLE
[Document] Stack is LIFO not FIFO

### ISSUE THREAD

**Issue by jyorien** [aquova/chip8-book#6]
Hi, not sure if the book issues are meant to be opened here, but I did not know where to post it.
I was wondering if there was a mistake in this section as you mentioned Stack but described it as FIFO even though it is usually LIFO and the pancake example sounds like a LIFO example as well?

<img width="748" alt="image" src="https://user-images.githubusercontent.com/58991251/190952503-d3d73289-8886-4b0c-930a-7aa1bfcfa5b4.png">

**Comment by aquova** [comment]
You are correct. Fixed in cc7d586031df0744b4e30f78c9be2a6a81ca6919
